<<<<<<< HEAD:src/BackendDjango/reviews/migrations/0002_remove_review_diffculty_review_course_num_and_more.py
# Generated by Django 4.0.1 on 2022-01-16 06:07
=======
# Generated by Django 3.1.3 on 2022-01-16 07:16
>>>>>>> 9fbf28a1cda721a8d66644319005dcf909f559b1:src/BackendDjango/reviews/migrations/0002_auto_20220115_2316.py

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='diffculty',
        ),
        migrations.AddField(
            model_name='review',
            name='course_num',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='difficulty',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='interest',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='usefulness',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='workload',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='overall_rate',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='semester',
            field=models.CharField(blank=True, choices=[('FALL', 'Fall'), ('WINTER', 'Winter'), ('SPRING', 'Spring'), ('SUMMER', 'Summer')], max_length=10),
        ),
    ]
