# Generated by Django 3.1.3 on 2022-01-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_diffculty_review_course_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ccid',
            field=models.CharField(default='anonymous', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='subject',
            field=models.CharField(default='CMPUT', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='course_num',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
