# Generated by Django 4.0.1 on 2022-01-15 23:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_prefix_alter_review_id_alter_review_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='prefix',
        ),
        migrations.AddField(
            model_name='review',
            name='course_num',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
