# Generated by Django 3.1.3 on 2022-01-16 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220115_1549'),
        ('reviews', '0003_remove_review_prefix_review_course_num'),
    ]

    operations = [
    ]
