# Generated by Django 4.0.1 on 2022-01-15 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(default='CMPUT', max_length=10)),
                ('courseCode', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=50)),
                ('topics', models.CharField(max_length=200)),
            ],
        ),
    ]
