# Generated by Django 4.0.1 on 2022-01-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='prefix',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='course',
            name='courseCode',
        ),
        migrations.AddField(
            model_name='course',
            name='assignedProfs',
            field=models.CharField(default='TBA', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.CharField(default='Faculty of Science', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='hasLab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='topics',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
