# Generated by Django 3.1.3 on 2022-01-16 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='prefix',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='course',
            name='courseCode',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='topics',
        ),
        migrations.AddField(
            model_name='course',
            name='assignedProfs',
            field=models.CharField(default='TBA', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='average_difficulty',
            field=models.FloatField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='course',
            name='average_interest',
            field=models.FloatField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='course',
            name='average_usefulness',
            field=models.FloatField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='course',
            name='average_workload',
            field=models.FloatField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='course',
            name='course_num',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.CharField(default='Faculty of Science', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='course',
            name='hasLab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.IntegerField(default=60, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
