# Generated by Django 3.1.3 on 2022-01-16 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_prefix_course_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
        migrations.AddField(
            model_name='course',
            name='average_overall',
            field=models.FloatField(default=2.5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
