# Generated by Django 3.1.3 on 2022-01-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20220115_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='course_num',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
