# Generated by Django 4.0.1 on 2022-01-16 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_difficulty_remove_course_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='difficulty_level',
            new_name='average_difficulty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_num',
        ),
        migrations.AddField(
            model_name='course',
            name='average_interest',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='course',
            name='average_usefulness',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='course',
            name='average_workload',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
