# Generated by Django 3.2.11 on 2022-01-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20220116_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.CharField(default='Science', max_length=30),
        ),
    ]
