# Generated by Django 3.1.3 on 2022-01-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_course_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='number',
            new_name='course_num',
        ),
    ]
